// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  type CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  type ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type Character = {
  owner: Identity,
  id: string,
  name: string,
  race: string,
  profession: string,
  specialization: string,
  startingRegion: string,
  createdAt: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Character {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("owner", AlgebraicType.createIdentityType()),
      new ProductTypeElement("id", AlgebraicType.createStringType()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("race", AlgebraicType.createStringType()),
      new ProductTypeElement("profession", AlgebraicType.createStringType()),
      new ProductTypeElement("specialization", AlgebraicType.createStringType()),
      new ProductTypeElement("startingRegion", AlgebraicType.createStringType()),
      new ProductTypeElement("createdAt", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Character): void {
    Character.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Character {
    return Character.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


