// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  type CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  type ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { type Character } from "./character_type";
import { type EventContext, type Reducer, type RemoteReducers, type RemoteTables } from ".";

/**
 * Table handle for the table `character`.
 *
 * Obtain a handle from the [`character`] property on [`RemoteTables`],
 * like `ctx.db.character`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.character.on_insert(...)`.
 */
export class CharacterTableHandle {
  tableCache: TableCache<Character>;

  constructor(tableCache: TableCache<Character>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Character> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `userId` unique index on the table `character`,
   * which allows point queries on the field of the same name
   * via the [`CharacterUserIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.character.userId().find(...)`.
   *
   * Get a handle on the `userId` unique index on the table `character`.
   */
  userId = {
    // Find the subscribed row whose `userId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: Identity): Character | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.userId, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `characterId` unique index on the table `character`,
   * which allows point queries on the field of the same name
   * via the [`CharacterCharacterIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.character.characterId().find(...)`.
   *
   * Get a handle on the `characterId` unique index on the table `character`.
   */
  characterId = {
    // Find the subscribed row whose `characterId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): Character | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.characterId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Character) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Character) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Character) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Character) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Character, newRow: Character) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Character, newRow: Character) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
