// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  type CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  type ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type Npc = {
  npcId: string,
  name: string,
  description: string,
  race: string,
  profession: string,
  maxHealth: number,
  currentHealth: number,
  maxMana: number,
  currentMana: number,
  abilities: string,
  regionId: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Npc {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("npcId", AlgebraicType.createStringType()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("description", AlgebraicType.createStringType()),
      new ProductTypeElement("race", AlgebraicType.createStringType()),
      new ProductTypeElement("profession", AlgebraicType.createStringType()),
      new ProductTypeElement("maxHealth", AlgebraicType.createI32Type()),
      new ProductTypeElement("currentHealth", AlgebraicType.createI32Type()),
      new ProductTypeElement("maxMana", AlgebraicType.createI32Type()),
      new ProductTypeElement("currentMana", AlgebraicType.createI32Type()),
      new ProductTypeElement("abilities", AlgebraicType.createStringType()),
      new ProductTypeElement("regionId", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Npc): void {
    Npc.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Npc {
    return Npc.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


