// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  type CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  type ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Npc } from "./npc_type";
import { type EventContext, type Reducer, type RemoteReducers, type RemoteTables } from ".";

/**
 * Table handle for the table `npc`.
 *
 * Obtain a handle from the [`npc`] property on [`RemoteTables`],
 * like `ctx.db.npc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.npc.on_insert(...)`.
 */
export class NpcTableHandle {
  tableCache: TableCache<Npc>;

  constructor(tableCache: TableCache<Npc>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Npc> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `npcId` unique index on the table `npc`,
   * which allows point queries on the field of the same name
   * via the [`NpcNpcIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.npc.npcId().find(...)`.
   *
   * Get a handle on the `npcId` unique index on the table `npc`.
   */
  npcId = {
    // Find the subscribed row whose `npcId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): Npc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.npcId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Npc) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Npc) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Npc) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Npc) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Npc, newRow: Npc) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Npc, newRow: Npc) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
