// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  type CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  type ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  type SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { Region } from "./region_type";
import { type EventContext, type Reducer, type RemoteReducers, type RemoteTables } from ".";

/**
 * Table handle for the table `region`.
 *
 * Obtain a handle from the [`region`] property on [`RemoteTables`],
 * like `ctx.db.region`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.region.on_insert(...)`.
 */
export class RegionTableHandle {
  tableCache: TableCache<Region>;

  constructor(tableCache: TableCache<Region>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Region> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `regionId` unique index on the table `region`,
   * which allows point queries on the field of the same name
   * via the [`RegionRegionIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.region.regionId().find(...)`.
   *
   * Get a handle on the `regionId` unique index on the table `region`.
   */
  regionId = {
    // Find the subscribed row whose `regionId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): Region | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.regionId, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Region) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Region) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Region) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Region) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Region, newRow: Region) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Region, newRow: Region) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
