// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Characters", {
  id: __t.string(),
  ownerId: __t.identity(),
  name: __t.string(),
  race: __t.string(),
  archetype: __t.string(),
  professionJson: __t.string(),
  statsJson: __t.string(),
});


