// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.8.0 (commit 549f84c80846137ec1ef7468d01673a329c0501f).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { Init } from "./init_reducer.ts";
export { Init };
import { OnDisconnect } from "./on_disconnect_reducer.ts";
export { OnDisconnect };
import { OnConnect } from "./on_connect_reducer.ts";
export { OnConnect };
import { LoginWithGoogleId } from "./login_with_google_id_reducer.ts";
export { LoginWithGoogleId };
import { Logout } from "./logout_reducer.ts";
export { Logout };
import { ApplyIntent } from "./apply_intent_reducer.ts";
export { ApplyIntent };
import { Tick } from "./tick_reducer.ts";
export { Tick };

// Import and reexport all table handle types
import { CharactersTableHandle } from "./characters_table.ts";
export { CharactersTableHandle };
import { NarrativeEventsTableHandle } from "./narrative_events_table.ts";
export { NarrativeEventsTableHandle };
import { SessionsTableHandle } from "./sessions_table.ts";
export { SessionsTableHandle };
import { UsersTableHandle } from "./users_table.ts";
export { UsersTableHandle };

// Import and reexport all types
import { Characters } from "./characters_type.ts";
export { Characters };
import { NarrativeEvents } from "./narrative_events_type.ts";
export { NarrativeEvents };
import { Sessions } from "./sessions_type.ts";
export { Sessions };
import { Users } from "./users_type.ts";
export { Users };

const REMOTE_MODULE = {
  tables: {
    characters: {
      tableName: "characters" as const,
      rowType: Characters.getTypeScriptAlgebraicType(),
    },
    narrative_events: {
      tableName: "narrative_events" as const,
      rowType: NarrativeEvents.getTypeScriptAlgebraicType(),
    },
    sessions: {
      tableName: "sessions" as const,
      rowType: Sessions.getTypeScriptAlgebraicType(),
    },
    users: {
      tableName: "users" as const,
      rowType: Users.getTypeScriptAlgebraicType(),
      primaryKey: "id",
      primaryKeyInfo: {
        colName: "id",
        colType: (Users.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    init: {
      reducerName: "init",
      argsType: Init.getTypeScriptAlgebraicType(),
    },
    on_disconnect: {
      reducerName: "on_disconnect",
      argsType: OnDisconnect.getTypeScriptAlgebraicType(),
    },
    on_connect: {
      reducerName: "on_connect",
      argsType: OnConnect.getTypeScriptAlgebraicType(),
    },
    login_with_google_id: {
      reducerName: "login_with_google_id",
      argsType: LoginWithGoogleId.getTypeScriptAlgebraicType(),
    },
    logout: {
      reducerName: "logout",
      argsType: Logout.getTypeScriptAlgebraicType(),
    },
    apply_intent: {
      reducerName: "apply_intent",
      argsType: ApplyIntent.getTypeScriptAlgebraicType(),
    },
    tick: {
      reducerName: "tick",
      argsType: Tick.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.8.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "Init", args: Init }
| { name: "OnDisconnect", args: OnDisconnect }
| { name: "OnConnect", args: OnConnect }
| { name: "LoginWithGoogleId", args: LoginWithGoogleId }
| { name: "Logout", args: Logout }
| { name: "ApplyIntent", args: ApplyIntent }
| { name: "Tick", args: Tick }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  init() {
    this.connection.callReducer("init", new Uint8Array(0), this.setCallReducerFlags.initFlags);
  }

  onInit(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("init", callback);
  }

  removeOnInit(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("init", callback);
  }

  onOnDisconnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("on_disconnect", callback);
  }

  removeOnOnDisconnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("on_disconnect", callback);
  }

  onOnConnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("on_connect", callback);
  }

  removeOnOnConnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("on_connect", callback);
  }

  loginWithGoogleId(deviceId: string | undefined, email: string) {
    const __args = { deviceId, email };
    let __writer = new __BinaryWriter(1024);
    LoginWithGoogleId.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("login_with_google_id", __argsBuffer, this.setCallReducerFlags.loginWithGoogleIdFlags);
  }

  onLoginWithGoogleId(callback: (ctx: ReducerEventContext, deviceId: string | undefined, email: string) => void) {
    this.connection.onReducer("login_with_google_id", callback);
  }

  removeOnLoginWithGoogleId(callback: (ctx: ReducerEventContext, deviceId: string | undefined, email: string) => void) {
    this.connection.offReducer("login_with_google_id", callback);
  }

  logout() {
    this.connection.callReducer("logout", new Uint8Array(0), this.setCallReducerFlags.logoutFlags);
  }

  onLogout(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("logout", callback);
  }

  removeOnLogout(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("logout", callback);
  }

  applyIntent(intentJson: string) {
    const __args = { intentJson };
    let __writer = new __BinaryWriter(1024);
    ApplyIntent.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("apply_intent", __argsBuffer, this.setCallReducerFlags.applyIntentFlags);
  }

  onApplyIntent(callback: (ctx: ReducerEventContext, intentJson: string) => void) {
    this.connection.onReducer("apply_intent", callback);
  }

  removeOnApplyIntent(callback: (ctx: ReducerEventContext, intentJson: string) => void) {
    this.connection.offReducer("apply_intent", callback);
  }

  tick() {
    this.connection.callReducer("tick", new Uint8Array(0), this.setCallReducerFlags.tickFlags);
  }

  onTick(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("tick", callback);
  }

  removeOnTick(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("tick", callback);
  }

}

export class SetReducerFlags {
  initFlags: __CallReducerFlags = 'FullUpdate';
  init(flags: __CallReducerFlags) {
    this.initFlags = flags;
  }

  loginWithGoogleIdFlags: __CallReducerFlags = 'FullUpdate';
  loginWithGoogleId(flags: __CallReducerFlags) {
    this.loginWithGoogleIdFlags = flags;
  }

  logoutFlags: __CallReducerFlags = 'FullUpdate';
  logout(flags: __CallReducerFlags) {
    this.logoutFlags = flags;
  }

  applyIntentFlags: __CallReducerFlags = 'FullUpdate';
  applyIntent(flags: __CallReducerFlags) {
    this.applyIntentFlags = flags;
  }

  tickFlags: __CallReducerFlags = 'FullUpdate';
  tick(flags: __CallReducerFlags) {
    this.tickFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get characters(): CharactersTableHandle<'characters'> {
    // clientCache is a private property
    return new CharactersTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Characters>(REMOTE_MODULE.tables.characters));
  }

  get narrativeEvents(): NarrativeEventsTableHandle<'narrative_events'> {
    // clientCache is a private property
    return new NarrativeEventsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<NarrativeEvents>(REMOTE_MODULE.tables.narrative_events));
  }

  get sessions(): SessionsTableHandle<'sessions'> {
    // clientCache is a private property
    return new SessionsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Sessions>(REMOTE_MODULE.tables.sessions));
  }

  get users(): UsersTableHandle<'users'> {
    // clientCache is a private property
    return new UsersTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Users>(REMOTE_MODULE.tables.users));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
