// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type AddCharacter = {
  name: string,
  description: string,
  race: string,
  archetype: string,
  profession: string,
  startingRegion: string,
  strength: number,
  dexterity: number,
  intelligence: number,
  constitution: number,
  wisdom: number,
  charisma: number,
  maxHealth: number,
  currentHealth: number,
  maxMana: number,
  currentMana: number,
  raceAbilities: string,
  professionAbilities: string,
  level: number,
  xp: number,
  equippedWeapon: string,
};
let _cached_AddCharacter_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const AddCharacter = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_AddCharacter_type_value) return _cached_AddCharacter_type_value;
    _cached_AddCharacter_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_AddCharacter_type_value.value.elements.push(
      { name: "name", algebraicType: __AlgebraicTypeValue.String },
      { name: "description", algebraicType: __AlgebraicTypeValue.String },
      { name: "race", algebraicType: __AlgebraicTypeValue.String },
      { name: "archetype", algebraicType: __AlgebraicTypeValue.String },
      { name: "profession", algebraicType: __AlgebraicTypeValue.String },
      { name: "startingRegion", algebraicType: __AlgebraicTypeValue.String },
      { name: "strength", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "dexterity", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "intelligence", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "constitution", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "wisdom", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "charisma", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "maxHealth", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "currentHealth", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "maxMana", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "currentMana", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "raceAbilities", algebraicType: __AlgebraicTypeValue.String },
      { name: "professionAbilities", algebraicType: __AlgebraicTypeValue.String },
      { name: "level", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "xp", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "equippedWeapon", algebraicType: __AlgebraicTypeValue.String },
    );
    return _cached_AddCharacter_type_value;
  },

  serialize(writer: __BinaryWriter, value: AddCharacter): void {
    __AlgebraicTypeValue.serializeValue(writer, AddCharacter.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AddCharacter {
    return __AlgebraicTypeValue.deserializeValue(reader, AddCharacter.getTypeScriptAlgebraicType());
  },

}

export default AddCharacter;

