// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.8.0 (commit 549f84c80846137ec1ef7468d01673a329c0501f).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { SetName } from "./set_name_reducer.ts";
export { SetName };
import { AddCharacter } from "./add_character_reducer.ts";
export { AddCharacter };
import { UpdateCharacter } from "./update_character_reducer.ts";
export { UpdateCharacter };
import { ClearCharacters } from "./clear_characters_reducer.ts";
export { ClearCharacters };
import { CreateNpc } from "./create_npc_reducer.ts";
export { CreateNpc };
import { AddQuest } from "./add_quest_reducer.ts";
export { AddQuest };
import { CreateStarterRegion } from "./create_starter_region_reducer.ts";
export { CreateStarterRegion };
import { LinkRegions } from "./link_regions_reducer.ts";
export { LinkRegions };
import { CreateAndLinkNewRegion } from "./create_and_link_new_region_reducer.ts";
export { CreateAndLinkNewRegion };
import { OnConnect } from "./on_connect_reducer.ts";
export { OnConnect };
import { OnDisconnect } from "./on_disconnect_reducer.ts";
export { OnDisconnect };
import { ClearUsers } from "./clear_users_reducer.ts";
export { ClearUsers };

// Import and reexport all table handle types
import { CharacterTableHandle } from "./character_table.ts";
export { CharacterTableHandle };
import { NpcTableHandle } from "./npc_table.ts";
export { NpcTableHandle };
import { QuestTableHandle } from "./quest_table.ts";
export { QuestTableHandle };
import { RegionTableHandle } from "./region_table.ts";
export { RegionTableHandle };
import { UserTableHandle } from "./user_table.ts";
export { UserTableHandle };

// Import and reexport all types
import { Character } from "./character_type.ts";
export { Character };
import { Npc } from "./npc_type.ts";
export { Npc };
import { Quest } from "./quest_type.ts";
export { Quest };
import { Region } from "./region_type.ts";
export { Region };
import { User } from "./user_type.ts";
export { User };

const REMOTE_MODULE = {
  tables: {
    character: {
      tableName: "character" as const,
      rowType: Character.getTypeScriptAlgebraicType(),
      primaryKey: "characterId",
      primaryKeyInfo: {
        colName: "characterId",
        colType: (Character.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[1].algebraicType,
      },
    },
    npc: {
      tableName: "npc" as const,
      rowType: Npc.getTypeScriptAlgebraicType(),
      primaryKey: "npcId",
      primaryKeyInfo: {
        colName: "npcId",
        colType: (Npc.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    quest: {
      tableName: "quest" as const,
      rowType: Quest.getTypeScriptAlgebraicType(),
      primaryKey: "questId",
      primaryKeyInfo: {
        colName: "questId",
        colType: (Quest.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    region: {
      tableName: "region" as const,
      rowType: Region.getTypeScriptAlgebraicType(),
      primaryKey: "regionId",
      primaryKeyInfo: {
        colName: "regionId",
        colType: (Region.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    user: {
      tableName: "user" as const,
      rowType: User.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
      primaryKeyInfo: {
        colName: "identity",
        colType: (User.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    set_name: {
      reducerName: "set_name",
      argsType: SetName.getTypeScriptAlgebraicType(),
    },
    add_character: {
      reducerName: "add_character",
      argsType: AddCharacter.getTypeScriptAlgebraicType(),
    },
    update_character: {
      reducerName: "update_character",
      argsType: UpdateCharacter.getTypeScriptAlgebraicType(),
    },
    clear_characters: {
      reducerName: "clear_characters",
      argsType: ClearCharacters.getTypeScriptAlgebraicType(),
    },
    create_npc: {
      reducerName: "create_npc",
      argsType: CreateNpc.getTypeScriptAlgebraicType(),
    },
    add_quest: {
      reducerName: "add_quest",
      argsType: AddQuest.getTypeScriptAlgebraicType(),
    },
    create_starter_region: {
      reducerName: "create_starter_region",
      argsType: CreateStarterRegion.getTypeScriptAlgebraicType(),
    },
    link_regions: {
      reducerName: "link_regions",
      argsType: LinkRegions.getTypeScriptAlgebraicType(),
    },
    create_and_link_new_region: {
      reducerName: "create_and_link_new_region",
      argsType: CreateAndLinkNewRegion.getTypeScriptAlgebraicType(),
    },
    on_connect: {
      reducerName: "on_connect",
      argsType: OnConnect.getTypeScriptAlgebraicType(),
    },
    on_disconnect: {
      reducerName: "on_disconnect",
      argsType: OnDisconnect.getTypeScriptAlgebraicType(),
    },
    clear_users: {
      reducerName: "clear_users",
      argsType: ClearUsers.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.8.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "SetName", args: SetName }
| { name: "AddCharacter", args: AddCharacter }
| { name: "UpdateCharacter", args: UpdateCharacter }
| { name: "ClearCharacters", args: ClearCharacters }
| { name: "CreateNpc", args: CreateNpc }
| { name: "AddQuest", args: AddQuest }
| { name: "CreateStarterRegion", args: CreateStarterRegion }
| { name: "LinkRegions", args: LinkRegions }
| { name: "CreateAndLinkNewRegion", args: CreateAndLinkNewRegion }
| { name: "OnConnect", args: OnConnect }
| { name: "OnDisconnect", args: OnDisconnect }
| { name: "ClearUsers", args: ClearUsers }
;

export class RemoteReducers {
  connection: __DbConnectionImpl;
  setCallReducerFlags: SetReducerFlags;
  constructor(connection: __DbConnectionImpl, setCallReducerFlags: SetReducerFlags) {
    this.connection = connection;
    this.setCallReducerFlags = setCallReducerFlags;
  }

  setName(name: string) {
    const __args = { name };
    let __writer = new __BinaryWriter(1024);
    SetName.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("set_name", __argsBuffer, this.setCallReducerFlags.setNameFlags);
  }

  onSetName(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.onReducer("set_name", callback);
  }

  removeOnSetName(callback: (ctx: ReducerEventContext, name: string) => void) {
    this.connection.offReducer("set_name", callback);
  }

  addCharacter(name: string, description: string, race: string, archetype: string, profession: string, startingRegion: string, strength: number, dexterity: number, intelligence: number, constitution: number, wisdom: number, charisma: number, maxHealth: number, currentHealth: number, maxMana: number, currentMana: number, raceAbilities: string, professionAbilities: string, level: number, xp: number, equippedWeapon: string) {
    const __args = { name, description, race, archetype, profession, startingRegion, strength, dexterity, intelligence, constitution, wisdom, charisma, maxHealth, currentHealth, maxMana, currentMana, raceAbilities, professionAbilities, level, xp, equippedWeapon };
    let __writer = new __BinaryWriter(1024);
    AddCharacter.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_character", __argsBuffer, this.setCallReducerFlags.addCharacterFlags);
  }

  onAddCharacter(callback: (ctx: ReducerEventContext, name: string, description: string, race: string, archetype: string, profession: string, startingRegion: string, strength: number, dexterity: number, intelligence: number, constitution: number, wisdom: number, charisma: number, maxHealth: number, currentHealth: number, maxMana: number, currentMana: number, raceAbilities: string, professionAbilities: string, level: number, xp: number, equippedWeapon: string) => void) {
    this.connection.onReducer("add_character", callback);
  }

  removeOnAddCharacter(callback: (ctx: ReducerEventContext, name: string, description: string, race: string, archetype: string, profession: string, startingRegion: string, strength: number, dexterity: number, intelligence: number, constitution: number, wisdom: number, charisma: number, maxHealth: number, currentHealth: number, maxMana: number, currentMana: number, raceAbilities: string, professionAbilities: string, level: number, xp: number, equippedWeapon: string) => void) {
    this.connection.offReducer("add_character", callback);
  }

  updateCharacter(characterId: string, name: string | undefined, description: string | undefined, currentLocation: string | undefined, strength: number | undefined, dexterity: number | undefined, intelligence: number | undefined, constitution: number | undefined, wisdom: number | undefined, charisma: number | undefined, maxHealth: number | undefined, currentHealth: number | undefined, maxMana: number | undefined, currentMana: number | undefined, raceAbilities: string | undefined, professionAbilities: string | undefined, armorType: string | undefined, inventoryItems: string | undefined, head: string | undefined, shoulders: string | undefined, back: string | undefined, chest: string | undefined, arms: string | undefined, hands: string | undefined, legs: string | undefined, feet: string | undefined, rings: string | undefined, necklace: string | undefined, earrings: string | undefined, relic: string | undefined, equippedWeapon: string | undefined) {
    const __args = { characterId, name, description, currentLocation, strength, dexterity, intelligence, constitution, wisdom, charisma, maxHealth, currentHealth, maxMana, currentMana, raceAbilities, professionAbilities, armorType, inventoryItems, head, shoulders, back, chest, arms, hands, legs, feet, rings, necklace, earrings, relic, equippedWeapon };
    let __writer = new __BinaryWriter(1024);
    UpdateCharacter.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_character", __argsBuffer, this.setCallReducerFlags.updateCharacterFlags);
  }

  onUpdateCharacter(callback: (ctx: ReducerEventContext, characterId: string, name: string | undefined, description: string | undefined, currentLocation: string | undefined, strength: number | undefined, dexterity: number | undefined, intelligence: number | undefined, constitution: number | undefined, wisdom: number | undefined, charisma: number | undefined, maxHealth: number | undefined, currentHealth: number | undefined, maxMana: number | undefined, currentMana: number | undefined, raceAbilities: string | undefined, professionAbilities: string | undefined, armorType: string | undefined, inventoryItems: string | undefined, head: string | undefined, shoulders: string | undefined, back: string | undefined, chest: string | undefined, arms: string | undefined, hands: string | undefined, legs: string | undefined, feet: string | undefined, rings: string | undefined, necklace: string | undefined, earrings: string | undefined, relic: string | undefined, equippedWeapon: string | undefined) => void) {
    this.connection.onReducer("update_character", callback);
  }

  removeOnUpdateCharacter(callback: (ctx: ReducerEventContext, characterId: string, name: string | undefined, description: string | undefined, currentLocation: string | undefined, strength: number | undefined, dexterity: number | undefined, intelligence: number | undefined, constitution: number | undefined, wisdom: number | undefined, charisma: number | undefined, maxHealth: number | undefined, currentHealth: number | undefined, maxMana: number | undefined, currentMana: number | undefined, raceAbilities: string | undefined, professionAbilities: string | undefined, armorType: string | undefined, inventoryItems: string | undefined, head: string | undefined, shoulders: string | undefined, back: string | undefined, chest: string | undefined, arms: string | undefined, hands: string | undefined, legs: string | undefined, feet: string | undefined, rings: string | undefined, necklace: string | undefined, earrings: string | undefined, relic: string | undefined, equippedWeapon: string | undefined) => void) {
    this.connection.offReducer("update_character", callback);
  }

  clearCharacters() {
    this.connection.callReducer("clear_characters", new Uint8Array(0), this.setCallReducerFlags.clearCharactersFlags);
  }

  onClearCharacters(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("clear_characters", callback);
  }

  removeOnClearCharacters(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("clear_characters", callback);
  }

  createNpc(name: string, description: string, race: string, profession: string, maxHealth: number, currentHealth: number, maxMana: number, currentMana: number, abilities: string, regionId: string) {
    const __args = { name, description, race, profession, maxHealth, currentHealth, maxMana, currentMana, abilities, regionId };
    let __writer = new __BinaryWriter(1024);
    CreateNpc.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_npc", __argsBuffer, this.setCallReducerFlags.createNpcFlags);
  }

  onCreateNpc(callback: (ctx: ReducerEventContext, name: string, description: string, race: string, profession: string, maxHealth: number, currentHealth: number, maxMana: number, currentMana: number, abilities: string, regionId: string) => void) {
    this.connection.onReducer("create_npc", callback);
  }

  removeOnCreateNpc(callback: (ctx: ReducerEventContext, name: string, description: string, race: string, profession: string, maxHealth: number, currentHealth: number, maxMana: number, currentMana: number, abilities: string, regionId: string) => void) {
    this.connection.offReducer("create_npc", callback);
  }

  addQuest(npcId: string, name: string, description: string, steps: number, reward: string, penalty: string, type: string, repeatable: boolean) {
    const __args = { npcId, name, description, steps, reward, penalty, type, repeatable };
    let __writer = new __BinaryWriter(1024);
    AddQuest.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_quest", __argsBuffer, this.setCallReducerFlags.addQuestFlags);
  }

  onAddQuest(callback: (ctx: ReducerEventContext, npcId: string, name: string, description: string, steps: number, reward: string, penalty: string, type: string, repeatable: boolean) => void) {
    this.connection.onReducer("add_quest", callback);
  }

  removeOnAddQuest(callback: (ctx: ReducerEventContext, npcId: string, name: string, description: string, steps: number, reward: string, penalty: string, type: string, repeatable: boolean) => void) {
    this.connection.offReducer("add_quest", callback);
  }

  createStarterRegion(name: string, description: string, fullDescription: string, climate: string, culture: string, resources: string[]) {
    const __args = { name, description, fullDescription, climate, culture, resources };
    let __writer = new __BinaryWriter(1024);
    CreateStarterRegion.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_starter_region", __argsBuffer, this.setCallReducerFlags.createStarterRegionFlags);
  }

  onCreateStarterRegion(callback: (ctx: ReducerEventContext, name: string, description: string, fullDescription: string, climate: string, culture: string, resources: string[]) => void) {
    this.connection.onReducer("create_starter_region", callback);
  }

  removeOnCreateStarterRegion(callback: (ctx: ReducerEventContext, name: string, description: string, fullDescription: string, climate: string, culture: string, resources: string[]) => void) {
    this.connection.offReducer("create_starter_region", callback);
  }

  linkRegions(regionAId: string, regionBId: string) {
    const __args = { regionAId, regionBId };
    let __writer = new __BinaryWriter(1024);
    LinkRegions.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("link_regions", __argsBuffer, this.setCallReducerFlags.linkRegionsFlags);
  }

  onLinkRegions(callback: (ctx: ReducerEventContext, regionAId: string, regionBId: string) => void) {
    this.connection.onReducer("link_regions", callback);
  }

  removeOnLinkRegions(callback: (ctx: ReducerEventContext, regionAId: string, regionBId: string) => void) {
    this.connection.offReducer("link_regions", callback);
  }

  createAndLinkNewRegion(fromRegionId: string, name: string, description: string, fullDescription: string, climate: string, culture: string, tier: number, travelEnergyCost: number, resources: string[]) {
    const __args = { fromRegionId, name, description, fullDescription, climate, culture, tier, travelEnergyCost, resources };
    let __writer = new __BinaryWriter(1024);
    CreateAndLinkNewRegion.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_and_link_new_region", __argsBuffer, this.setCallReducerFlags.createAndLinkNewRegionFlags);
  }

  onCreateAndLinkNewRegion(callback: (ctx: ReducerEventContext, fromRegionId: string, name: string, description: string, fullDescription: string, climate: string, culture: string, tier: number, travelEnergyCost: number, resources: string[]) => void) {
    this.connection.onReducer("create_and_link_new_region", callback);
  }

  removeOnCreateAndLinkNewRegion(callback: (ctx: ReducerEventContext, fromRegionId: string, name: string, description: string, fullDescription: string, climate: string, culture: string, tier: number, travelEnergyCost: number, resources: string[]) => void) {
    this.connection.offReducer("create_and_link_new_region", callback);
  }

  onOnConnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("on_connect", callback);
  }

  removeOnOnConnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("on_connect", callback);
  }

  onOnDisconnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("on_disconnect", callback);
  }

  removeOnOnDisconnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("on_disconnect", callback);
  }

  clearUsers() {
    this.connection.callReducer("clear_users", new Uint8Array(0), this.setCallReducerFlags.clearUsersFlags);
  }

  onClearUsers(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("clear_users", callback);
  }

  removeOnClearUsers(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("clear_users", callback);
  }

}

export class SetReducerFlags {
  setNameFlags: __CallReducerFlags = 'FullUpdate';
  setName(flags: __CallReducerFlags) {
    this.setNameFlags = flags;
  }

  addCharacterFlags: __CallReducerFlags = 'FullUpdate';
  addCharacter(flags: __CallReducerFlags) {
    this.addCharacterFlags = flags;
  }

  updateCharacterFlags: __CallReducerFlags = 'FullUpdate';
  updateCharacter(flags: __CallReducerFlags) {
    this.updateCharacterFlags = flags;
  }

  clearCharactersFlags: __CallReducerFlags = 'FullUpdate';
  clearCharacters(flags: __CallReducerFlags) {
    this.clearCharactersFlags = flags;
  }

  createNpcFlags: __CallReducerFlags = 'FullUpdate';
  createNpc(flags: __CallReducerFlags) {
    this.createNpcFlags = flags;
  }

  addQuestFlags: __CallReducerFlags = 'FullUpdate';
  addQuest(flags: __CallReducerFlags) {
    this.addQuestFlags = flags;
  }

  createStarterRegionFlags: __CallReducerFlags = 'FullUpdate';
  createStarterRegion(flags: __CallReducerFlags) {
    this.createStarterRegionFlags = flags;
  }

  linkRegionsFlags: __CallReducerFlags = 'FullUpdate';
  linkRegions(flags: __CallReducerFlags) {
    this.linkRegionsFlags = flags;
  }

  createAndLinkNewRegionFlags: __CallReducerFlags = 'FullUpdate';
  createAndLinkNewRegion(flags: __CallReducerFlags) {
    this.createAndLinkNewRegionFlags = flags;
  }

  clearUsersFlags: __CallReducerFlags = 'FullUpdate';
  clearUsers(flags: __CallReducerFlags) {
    this.clearUsersFlags = flags;
  }

}

export class RemoteTables {
  connection: __DbConnectionImpl;
  constructor(connection: __DbConnectionImpl) {
    this.connection = connection;
  }

  get character(): CharacterTableHandle<'character'> {
    // clientCache is a private property
    return new CharacterTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Character>(REMOTE_MODULE.tables.character));
  }

  get npc(): NpcTableHandle<'npc'> {
    // clientCache is a private property
    return new NpcTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Npc>(REMOTE_MODULE.tables.npc));
  }

  get quest(): QuestTableHandle<'quest'> {
    // clientCache is a private property
    return new QuestTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Quest>(REMOTE_MODULE.tables.quest));
  }

  get region(): RegionTableHandle<'region'> {
    // clientCache is a private property
    return new RegionTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Region>(REMOTE_MODULE.tables.region));
  }

  get user(): UserTableHandle<'user'> {
    // clientCache is a private property
    return new UserTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<User>(REMOTE_MODULE.tables.user));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
